apiVersion: apps/v1
kind: Deployment
metadata:
  name: nguyendo2008-student
spec:
  replicas: 1
  selector:
    matchLabels:
        app: nguyendo2008
  template:
    metadata:
      labels:
        app: nguyendo2008
    spec:
      containers:
        - name: cont
          image: nguyendo2008/nc_student
          ports:
            - containerPort: 9090
              name: web
        resources:
            requests:
            memory: "50Mi"
            cpu: "50m"
            limits:
            memory: "75Mi"
            cpu: "75m"
